# Generated by Django 4.2.16 on 2025-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco',
            new_name='valor',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='qtde',
            field=models.IntegerField(),
        ),
    ]
