# Generated by Django 4.2.16 on 2025-01-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cliente_itempedido_produto_pedido_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
    ]
