# Generated by Django 4.2.16 on 2025-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_preco_itempedido_valor_alter_itempedido_qtde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='qtde',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
