# Generated by Django 4.2.16 on 2025-01-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Descrição padrão', verbose_name='Descrição do Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível para Venda'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10, verbose_name='Valor do Produto'),
        ),

        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Produto'),
        ),
    ]
