# Generated by Django 4.2.16 on 2025-01-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_produto_descricao_alter_produto_valor'),
    ]

    operations = [
        migrations.AddField(
        model_name='produto',
        name='categoria',
        field=models.ForeignKey(default=1, on_delete=models.CASCADE, to='home.Categoria'),
         ),
        migrations.AddField(
            model_name='produto',
            name='img_base64',
            field=models.TextField(blank=True, verbose_name='Imagem Base64'),
        ),
    ]
