# Generated by Django 4.2.16 on 2025-01-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_produto_categoria_produto_img_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria', verbose_name='Categoria'),
        ),
    ]
